/**
 * High-fidelity realistic log dataset and initial mock store
 */

export const INITIAL_STATS = {
  totalLogs: 12480,
  anomalies: 126,
  critical: 18,
  errorRate: 3.8,
  sources: 42,
  avgResponseTime: '142ms',
  detectionEngineStatus: 'Healthy',
  detectionEngineVersion: 'v2.4.1 (EWMA + Isolation Forest)',
  lastScanTimestamp: new Date().toISOString(),
};

export const SEVERITY_BREAKDOWN = {
  critical: 18,
  high: 46,
  medium: 39,
  low: 23,
};

export const TOP_ANOMALY_SOURCES = [
  { source: '10.0.0.55', count: 42, percentage: 33.3, country: 'US', riskLevel: 'CRITICAL', lastSeen: '2 mins ago' },
  { source: '203.0.113.7', count: 27, percentage: 21.4, country: 'DE', riskLevel: 'HIGH', lastSeen: '8 mins ago' },
  { source: '192.168.1.14', count: 18, percentage: 14.3, country: 'INTERNAL', riskLevel: 'CRITICAL', lastSeen: '14 mins ago' },
  { source: '198.51.100.22', count: 14, percentage: 11.1, country: 'SG', riskLevel: 'HIGH', lastSeen: '25 mins ago' },
  { source: '172.16.4.88', count: 9, percentage: 7.1, country: 'INTERNAL', riskLevel: 'MEDIUM', lastSeen: '40 mins ago' },
  { source: '45.33.32.156', count: 6, percentage: 4.8, country: 'NL', riskLevel: 'LOW', lastSeen: '1 hour ago' },
];

export const ACTIVITY_TIMELINE = [
  { time: '09:00', timestamp: '2026-08-24T09:00:00.000Z', totalLogs: 840, normalLogs: 828, highLogs: 10, criticalLogs: 2, anomalies: 12 },
  { time: '09:15', timestamp: '2026-08-24T09:15:00.000Z', totalLogs: 920, normalLogs: 908, highLogs: 9, criticalLogs: 3, anomalies: 12 },
  { time: '09:30', timestamp: '2026-08-24T09:30:00.000Z', totalLogs: 1150, normalLogs: 1122, highLogs: 20, criticalLogs: 8, anomalies: 28 },
  { time: '09:45', timestamp: '2026-08-24T09:45:00.000Z', totalLogs: 1420, normalLogs: 1375, highLogs: 35, criticalLogs: 10, anomalies: 45 },
  { time: '10:00', timestamp: '2026-08-24T10:00:00.000Z', totalLogs: 1680, normalLogs: 1618, highLogs: 48, criticalLogs: 14, anomalies: 62 },
  { time: '10:15', timestamp: '2026-08-24T10:15:00.000Z', totalLogs: 1950, normalLogs: 1864, highLogs: 68, criticalLogs: 18, anomalies: 86 },
  { time: '10:30', timestamp: '2026-08-24T10:30:00.000Z', totalLogs: 1540, normalLogs: 1495, highLogs: 33, criticalLogs: 12, anomalies: 45 },
  { time: '10:45', timestamp: '2026-08-24T10:45:00.000Z', totalLogs: 1280, normalLogs: 1256, highLogs: 18, criticalLogs: 6, anomalies: 24 },
  { time: '11:00', timestamp: '2026-08-24T11:00:00.000Z', totalLogs: 1100, normalLogs: 1086, highLogs: 11, criticalLogs: 3, anomalies: 14 },
];

export const INITIAL_LOGS = [
  {
    id: 'log-001',
    timestamp: '2026-08-24T10:15:10.421Z',
    source: '10.0.0.55',
    event: 'POST /api/payment',
    status: '500',
    severity: 'CRITICAL',
    message: 'Internal server error: Connection to Stripe Gateway timed out after 30000ms [TxID: #tx_88921]',
    rawLog: '{"timestamp":"2026-08-24T10:15:10.421Z","level":"ERROR","service":"payment-service","client_ip":"10.0.0.55","method":"POST","endpoint":"/api/payment","status_code":500,"duration_ms":30012,"error":"GatewayTimeout: Stripe API endpoint unreacheable","trace_id":"tr-998a-77c1","request_payload":{"amount":42900,"currency":"usd","customer_id":"cust_91823"}}',
    service: 'payment-service',
    responseTime: '30,012ms',
    isAnomaly: true,
    anomalyScore: 86,
    detectionEngineVersion: 'v2.4.1',
    detectionReasons: [
      { reason: 'HTTP 500 server error response', score: 40 },
      { reason: '5 failures from this IP in 60 seconds', score: 25 },
      { reason: 'Request rate 4.2× above baseline', score: 21 },
    ],
  },
  {
    id: 'log-002',
    timestamp: '2026-08-24T10:14:48.112Z',
    source: '203.0.113.7',
    event: 'POST /api/v1/auth/login',
    status: '401',
    severity: 'HIGH',
    message: 'Authentication failed for user admin@production.internal: Invalid cryptographic signature',
    rawLog: '{"timestamp":"2026-08-24T10:14:48.112Z","level":"WARN","service":"auth-service","client_ip":"203.0.113.7","method":"POST","endpoint":"/api/v1/auth/login","status_code":401,"duration_ms":145,"error":"InvalidSignatureException","user_agent":"python-requests/2.31.0","geo_country":"DE"}',
    service: 'auth-service',
    responseTime: '145ms',
    isAnomaly: true,
    anomalyScore: 78,
    detectionEngineVersion: 'v2.4.1',
    detectionReasons: [
      { reason: 'High frequency auth failure burst from single remote IP', score: 35 },
      { reason: 'Automated script User-Agent signature detected (python-requests)', score: 25 },
      { reason: 'Targeting privileged administrator credential namespace', score: 18 },
    ],
  },
  {
    id: 'log-003',
    timestamp: '2026-08-24T10:14:20.903Z',
    source: '192.168.1.14',
    event: 'GET /api/v1/orders/export',
    status: '504',
    severity: 'CRITICAL',
    message: 'Gateway Timeout: Database thread pool exhausted while processing large bulk CSV export',
    rawLog: '{"timestamp":"2026-08-24T10:14:20.903Z","level":"ERROR","service":"order-db","client_ip":"192.168.1.14","method":"GET","endpoint":"/api/v1/orders/export","status_code":504,"duration_ms":60004,"error":"PoolTimeoutException: No connections available in HikariPool-1","active_connections":100,"max_connections":100}',
    service: 'order-db',
    responseTime: '60,004ms',
    isAnomaly: true,
    anomalyScore: 91,
    detectionEngineVersion: 'v2.4.1',
    detectionReasons: [
      { reason: 'HTTP 504 Gateway Timeout (60s SLA breach)', score: 40 },
      { reason: 'Database connection pool starvation (100% saturation)', score: 30 },
      { reason: 'Query execution duration exceeded 99.9th percentile', score: 21 },
    ],
  },
  {
    id: 'log-004',
    timestamp: '2026-08-24T10:13:55.782Z',
    source: '198.51.100.22',
    event: 'POST /api/v2/webhooks/stripe',
    status: '429',
    severity: 'HIGH',
    message: 'Rate limit exceeded: 840 requests received in sliding 10s window (limit: 100/10s)',
    rawLog: '{"timestamp":"2026-08-24T10:13:55.782Z","level":"WARN","service":"api-gateway","client_ip":"198.51.100.22","method":"POST","endpoint":"/api/v2/webhooks/stripe","status_code":429,"duration_ms":12,"rate_limit_bucket":"ip:198.51.100.22","tokens_remaining":0}',
    service: 'api-gateway',
    responseTime: '12ms',
    isAnomaly: true,
    anomalyScore: 74,
    detectionEngineVersion: 'v2.4.1',
    detectionReasons: [
      { reason: 'Rate limit breached (HTTP 429 Too Many Requests)', score: 45 },
      { reason: 'Traffic surge 8.4× allowable baseline burst', score: 29 },
    ],
  },
  {
    id: 'log-005',
    timestamp: '2026-08-24T10:13:12.645Z',
    source: '10.0.0.55',
    event: 'POST /api/payment',
    status: '500',
    severity: 'CRITICAL',
    message: 'Internal server error: NullPointerException at PaymentProcessor.java:142',
    rawLog: '{"timestamp":"2026-08-24T10:13:12.645Z","level":"ERROR","service":"payment-service","client_ip":"10.0.0.55","method":"POST","endpoint":"/api/payment","status_code":500,"duration_ms":1205,"stack_trace":"java.lang.NullPointerException at com.loglens.payment.PaymentProcessor.execute(PaymentProcessor.java:142)"}',
    service: 'payment-service',
    responseTime: '1,205ms',
    isAnomaly: true,
    anomalyScore: 84,
    detectionEngineVersion: 'v2.4.1',
    detectionReasons: [
      { reason: 'HTTP 500 Unhandled NullPointerException', score: 40 },
      { reason: 'Correlated failure cluster with IP 10.0.0.55', score: 25 },
      { reason: 'Abrupt error cascade on critical transaction route', score: 19 },
    ],
  },
  {
    id: 'log-006',
    timestamp: '2026-08-24T10:12:30.010Z',
    source: '172.16.4.88',
    event: 'GET /api/v1/metrics',
    status: '200',
    severity: 'MEDIUM',
    message: 'Prometheus metrics scrape latency anomaly (2,840ms vs expected <80ms)',
    rawLog: '{"timestamp":"2026-08-24T10:12:30.010Z","level":"INFO","service":"monitoring-agent","client_ip":"172.16.4.88","method":"GET","endpoint":"/api/v1/metrics","status_code":200,"duration_ms":2840,"body_bytes":891230}',
    service: 'monitoring-agent',
    responseTime: '2,840ms',
    isAnomaly: true,
    anomalyScore: 48,
    detectionEngineVersion: 'v2.4.1',
    detectionReasons: [
      { reason: 'Response latency 35× above historical p95 baseline', score: 30 },
      { reason: 'High payload response buffer serialization delay', score: 18 },
    ],
  },
  {
    id: 'log-007',
    timestamp: '2026-08-24T10:11:59.200Z',
    source: '10.0.0.12',
    event: 'GET /api/v1/health',
    status: '200',
    severity: 'NORMAL',
    message: 'Liveness and readiness check healthy. All microservice subsystems nominal.',
    rawLog: '{"timestamp":"2026-08-24T10:11:59.200Z","level":"INFO","service":"health-checker","client_ip":"10.0.0.12","method":"GET","endpoint":"/api/v1/health","status_code":200,"duration_ms":4,"status":"UP"}',
    service: 'health-checker',
    responseTime: '4ms',
    isAnomaly: false,
    anomalyScore: 0,
    detectionEngineVersion: 'v2.4.1',
    detectionReasons: [],
  },
  {
    id: 'log-008',
    timestamp: '2026-08-24T10:11:42.871Z',
    source: '10.0.0.84',
    event: 'GET /api/v1/products/featured',
    status: '200',
    severity: 'NORMAL',
    message: 'Cache hit in Redis cluster. Retrieved 24 featured product entities.',
    rawLog: '{"timestamp":"2026-08-24T10:11:42.871Z","level":"INFO","service":"inventory-service","client_ip":"10.0.0.84","method":"GET","endpoint":"/api/v1/products/featured","status_code":200,"duration_ms":8,"cache":"HIT"}',
    service: 'inventory-service',
    responseTime: '8ms',
    isAnomaly: false,
    anomalyScore: 0,
    detectionEngineVersion: 'v2.4.1',
    detectionReasons: [],
  },
  {
    id: 'log-009',
    timestamp: '2026-08-24T10:11:15.312Z',
    source: '10.0.0.91',
    event: 'POST /api/v1/cart/items',
    status: '201',
    severity: 'NORMAL',
    message: 'Added SKU-99120 to shopping session session_99214.',
    rawLog: '{"timestamp":"2026-08-24T10:11:15.312Z","level":"INFO","service":"cart-service","client_ip":"10.0.0.91","method":"POST","endpoint":"/api/v1/cart/items","status_code":201,"duration_ms":22,"cart_id":"cart_77182"}',
    service: 'cart-service',
    responseTime: '22ms',
    isAnomaly: false,
    anomalyScore: 0,
    detectionEngineVersion: 'v2.4.1',
    detectionReasons: [],
  },
  {
    id: 'log-010',
    timestamp: '2026-08-24T10:10:50.045Z',
    source: '10.0.0.103',
    event: 'GET /api/v1/users/me',
    status: '200',
    severity: 'NORMAL',
    message: 'User profile retrieved successfully with valid JWT bearer token.',
    rawLog: '{"timestamp":"2026-08-24T10:10:50.045Z","level":"INFO","service":"user-service","client_ip":"10.0.0.103","method":"GET","endpoint":"/api/v1/users/me","status_code":200,"duration_ms":16,"user_id":"usr_44012"}',
    service: 'user-service',
    responseTime: '16ms',
    isAnomaly: false,
    anomalyScore: 0,
    detectionEngineVersion: 'v2.4.1',
    detectionReasons: [],
  },
  {
    id: 'log-011',
    timestamp: '2026-08-24T10:10:22.610Z',
    source: '203.0.113.7',
    event: 'POST /api/v1/auth/login',
    status: '401',
    severity: 'HIGH',
    message: 'Authentication failed for user root@loglens.internal: Password verification mismatch',
    rawLog: '{"timestamp":"2026-08-24T10:10:22.610Z","level":"WARN","service":"auth-service","client_ip":"203.0.113.7","method":"POST","endpoint":"/api/v1/auth/login","status_code":401,"duration_ms":152,"error":"PasswordMismatch"}',
    service: 'auth-service',
    responseTime: '152ms',
    isAnomaly: true,
    anomalyScore: 78,
    detectionEngineVersion: 'v2.4.1',
    detectionReasons: [
      { reason: 'Repeated authentication failure sequence', score: 35 },
      { reason: 'Targeting root administrative entity', score: 25 },
      { reason: 'Automated rapid polling signature', score: 18 },
    ],
  },
  {
    id: 'log-012',
    timestamp: '2026-08-24T10:09:40.118Z',
    source: '10.0.0.55',
    event: 'POST /api/payment',
    status: '500',
    severity: 'CRITICAL',
    message: 'Internal server error: Connection reset by peer on outbound payment gateway TLS socket',
    rawLog: '{"timestamp":"2026-08-24T10:09:40.118Z","level":"ERROR","service":"payment-service","client_ip":"10.0.0.55","method":"POST","endpoint":"/api/payment","status_code":500,"duration_ms":5400,"error":"SocketException: Connection reset by peer"}',
    service: 'payment-service',
    responseTime: '5,400ms',
    isAnomaly: true,
    anomalyScore: 86,
    detectionEngineVersion: 'v2.4.1',
    detectionReasons: [
      { reason: 'HTTP 500 server error', score: 40 },
      { reason: '5 failures from this IP in 60 seconds', score: 25 },
      { reason: 'Request rate 4.2× above baseline', score: 21 },
    ],
  }
];

export const MOCK_AI_RESPONSES = {
  'log-001': {
    whatHappened: 'The payment gateway microservice suffered an unhandled 30-second socket timeout while processing a high-value customer transaction ($429.00 USD). This caused an internal server error (HTTP 500) and dropped the active customer checkout session.',
    likelyCause: 'Outbound TCP connection socket starvation or network latency degradation between AWS us-east-1 and Stripe API gateway. Additionally, lack of fallback circuit-breaker caused thread pool backpressure.',
    recommendedNextStep: '1. Verify Stripe API service status. 2. Implement an automated exponential backoff with resilience4j circuit breaker on `/api/payment`. 3. Isolate client IP 10.0.0.55 to prevent retry-storm amplification.',
    analyzedAt: new Date().toISOString(),
    confidence: '96%',
    model: 'AI Root Cause Model v3.2',
  },
  'log-002': {
    whatHappened: 'A remote IP address (203.0.113.7 originating from Germany) triggered a rapid credential-stuffing probe against privileged administrator user accounts using an automated Python script (`python-requests/2.31.0`).',
    likelyCause: 'Distributed brute-force attack or automated bot attempting credential dictionary spray against the authentication endpoint without proper WAF rate throttling.',
    recommendedNextStep: '1. Enforce Cloudflare / WAF IP block on `203.0.113.7`. 2. Temporarily enforce CAPTCHA on consecutive failed auth attempts. 3. Audit access logs for any successful logins from this subnet in the last 24 hours.',
    analyzedAt: new Date().toISOString(),
    confidence: '99%',
    model: 'AI Root Cause Model v3.2',
  },
  'log-003': {
    whatHappened: 'A massive unpaginated CSV export query on `/api/v1/orders/export` locked the primary database connection pool (HikariPool-1) for 60 seconds, resulting in a gateway timeout (HTTP 504) and starving downstream order queries.',
    likelyCause: 'Unbounded full-table scan on the `orders` database table without cursor pagination or background asynchronous job dispatch.',
    recommendedNextStep: '1. Transition order exports from synchronous HTTP requests to asynchronous worker queues (Celery/BullMQ with S3 pre-signed URLs). 2. Increase maximum Hikari connection pool size from 100 to 150 with aggressive idle query timeouts.',
    analyzedAt: new Date().toISOString(),
    confidence: '94%',
    model: 'AI Root Cause Model v3.2',
  },
  'log-004': {
    whatHappened: 'Stripe webhook ingestion endpoint received 840 webhook calls within a 10-second window from IP 198.51.100.22, triggering API Gateway rate limiting (HTTP 429).',
    likelyCause: 'Webhook burst or re-delivery flood following third-party upstream webhook replay after a transient network partition.',
    recommendedNextStep: '1. Verify webhook signature idempotency keys in Redis. 2. Increase the burst bucket token allowance for authenticated Stripe webhook CIDR ranges.',
    analyzedAt: new Date().toISOString(),
    confidence: '92%',
    model: 'AI Root Cause Model v3.2',
  },
};
